### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by mathieuruellan** [abrenoch/piwigo-kodi#12]
I put the plugin on kodi 15.2 and piwigo 2.7.4
I've got an error: "There was a problem communicating with the server. Please check the configuration".
The url/login/password are fine.

**Comment by abrenoch** [comment]
Does the demo site (the pre-configured one) work for you?

**Comment by mathieuruellan** [comment]
Yes it's working fine with the demo site.
After a few experimentation, I think it come from an https url. If set http, it's ok.
That's weird, my ssl certificate if good.

**Comment by abrenoch** [comment]
Ah gotchya. My install is not on HTTPS (local network only) so have not tested HTTPS myself..

Glad it's working for you on HTTP at least.. I'll see if I can take a look at improving support there!

**Comment by juliencarnot** [comment]
I reproduced this bug using https://milo.piwigo.com/ (a featured piwigo site from the Piwigo commercial platform, supporting HTTPS) and trying to connect as guest. With more and more self-hosters or services forcing HTTPS (for good reasons), has there been progress on this issue?

**Comment by abrenoch** [comment]
@juliencarnot I have put any work into supporting HTTPS yet, but I just took a moment to look into how I may be able to implement support and it appears to be much more simple than I had anticipated.. Also I did not have an HTTPS instance of piwigo to try this out on, so thanks for the link!

I'll try and get this implemented tonight!

**Comment by abrenoch** [comment]
@juliencarnot Would you mind trying the latest updates to "addon.py" and let me know if they are working for you?

Things went okay for me, but I did run into a bug where there was not a JSON property with the image I had come to expect to see, so I set it to use the largest iteration of the image should the `element_url` property not exist

**Comment by juliencarnot** [comment]
@abrenoch Thanks for your quick fix! It works for me too. As far as image size, I would have to try it on a gallery with images straight out of the camera as original uploads: it does seem a bit longer to load than my previous tests, but it could also be my connexion... Adapting to the Kodi display screen resolution (automatically or via a setting) could be a great enhancement on slow connexions. Thanks again!

**Comment by abrenoch** [comment]
@juliencarnot Really glad to hear it is working for you!

I may opt to make the image size configurable (there is a branch of this project that someone had incorporated that into) for now, but I really like the idea of adapting to the screen resolution.

Please let me know if you run into any other trouble!
