### ISSUE TITLE
2.7 Support?

### ISSUE THREAD

**Issue by mhinch** [abrenoch/piwigo-kodi#13]
Any plans for a 2.7-compatible version of piwigo-kodi. I love both packages, but I'd love them even more if they worked well together!

**Comment by abrenoch** [comment]
to my knowledge the API between majority of the 2.x versions is pretty mush the same, so the version should not matter too much!

Is there anything specific not working for you and would you be able to provide a kodi log so we could troubleshoot?

**Comment by abrenoch** [comment]
Closing this issue as the 2.x version seems to be working fine for me..

Please reopen if you are still having issues!
