### ISSUE TITLE
Multi-language configuration?

### ISSUE THREAD

**Issue by valodiadeseynes** [abrenoch/piwigo-kodi#15]
Hi there,

Are you willing to make your plugin available in multiple languages? I'm willing to translate it into French if you're okay with that.

**Comment by abrenoch** [comment]
Hey there, I love the idea! Luckily there are not too many strings to translate either!

I'll try to get a chance to learn how to properly implement multiple language support (if you have any references please share), and I'll get you a list of all the relevant text that might need to be translated!

**Comment by abrenoch** [comment]
I setup a project on getlocalization.com to help facilitate translations:

https://www.getlocalization.com/piwigokodi/

I have not uploaded anything yet, but I'll be sure to let you know when I do!

**Comment by valodiadeseynes** [comment]
Great, I've registered and sent an application!

**Comment by abrenoch** [comment]
Just uploaded a master translation file to getlocalization, let me know if there is anything I can do to help!

**Comment by abrenoch** [comment]
Got the code updated to work with language files, so I'll be closing this - but I'll update the project once some translations are posted!

**Comment by valodiadeseynes** [comment]
Thanks but you need to accept my application on getlocalization otherwise I can't do anything.

**Comment by abrenoch** [comment]
@valodiadeseynes  Ah I may have misread the getlocalization conditions.. it looks like I can only have 1 user assigned to a free account (which is obviously occupied by me).

If you could look at:
https://github.com/abrenoch/piwigo-kodi/blob/master/resources/Language/English/strings.xml

That will contain all the strings that need translating.. If you are comfortable with it you can submit a pull request with your changes or just toss it up on pastebin or something.

Thanks for the help with this!
