### ISSUE TITLE
picture do not rotate

### ISSUE THREAD

**Issue by kreutpet** [abrenoch/piwigo-kodi#19]
Hi ,

just installed this addon and it is great to view our piwigo album on kodi.
i am using kodi 17.6 with current master of you addon

I recognized that pictures are not automatically rotated while viewing in kodi.
in the web page all pictures are shown correctly.

Any hint on a setting would be great
thx
peter

**Comment by abrenoch** [comment]
Hey there @kreutpet 

Do you know if the original picture that got uploaded to piwigo was rotated correctly? I'm wondering if maybe the rotation info is contained in the metadata (which I am not checking). If this is the case there might be a different API call I can make to piwigo to get the correct version... However this could possibly be a bug with piwigo as well if it is not supplying the correctly rotated image via the API.

Thanks for the heads up!

**Comment by kreutpet** [comment]
here some data to try get more understanding
[sample picture](https://drive.google.com/open?id=1gXkBUMvCbIOm0DsnNtvodf3R5nEpXvh9)

The picture if shown correctly on digikam with metadata orientation right,top in digikam.
This picture was then uploaded to piwigo. I piwigo web page the picture is correctly rotated.
When i view the picture in kodi piwigo addon the picture is turned left.

i actually looked at the plugin . I did not find code that handled the rotation.
Is this maybe a bug in kodi ?

**Comment by abrenoch** [comment]
Thanks a lot for the example image, that will be helpful! If you pull up the image directly in kodi (rather than using a plugin), does it show it rotated? If not then a bug in kodi seems plausible.

You are correct that this plugin isn't attempting to handle any metadata at all. I'm suspecting that the API call I make to piwigo provides a rendition of the image that is stripped of any metadata, and is not taking that rotational info into consideration when creating previews in different resolutions. Be that the case, we could either try a different API call (maybe even make it configurable), attempt to handle that rotation info via this plugin, or start bothering the piwigo team to implement a fix for this behavior. Getting the piwigo team to implement changes can be difficult in my experience unfortunately... I have actually been considering forking the project to focus more on expanding their API since my PRs do not seem to go anywhere.

**Comment by kreutpet** [comment]
i verified now and traced back to the converted jpg uploaded in piwigo. Uploaded and it is not show with correct rotation
![20171014214218-fdecd7b8](https://user-images.githubusercontent.com/6454170/48197264-9406d080-e355-11e8-8eba-3f5643e10342.jpg)
the picture seem to not have anymore the exif metadata.
I assume that this may get lost when the digikam export plugin converts of uploads the cr2 to an jpg.
I will investigate the digikam piwigo export functionality

**Comment by kreutpet** [comment]
i guess this is what needs to be done to get the metadata considered.
https://www.haefelfinger.ch/photography/2018/04/27/piwigo-metadata.html
will give this a try and report feedback
my understanding is that this only works while importing

**Comment by kreutpet** [comment]
i guess this is what needs to be done to get the metadata considered.
https://www.haefelfinger.ch/photography/2018/04/27/piwigo-metadata.html
will give this a try and report feedback
my understanding is that this only works while importing

**Comment by kreutpet** [comment]
i checked now in the digikam plugin 
only option available is resize.

i chancged the ../local/config/config.inc.php to 

```
<?php                                                                                        
                                                                                             
$conf['show_exif'] = true;                                                                                  
$conf['show_exif_fields'] = array(                                                                          
  'DateTimeOriginal',                                                                                       
  'Make',                                                                                                            
  'Model',                                                                                                           
  'ExposureProgram',                                                                                                 
  'FocalLengthIn35mmFilm',                                                                                           
  'FNumber',                                                                                                         
  'ExposureTime',                                                                                                              
  'ISOSpeedRatings',                                                                                                           
  'Flash',                                                                                                                     
  'WhiteBalance',
  'UserComment'
  );

$conf['show_iptc'] = true;
$conf['use_iptc'] = true;
?>

```
not the picture is shown correctly in the piwigo kodi plugin.

**Comment by abrenoch** [comment]
Hey great job figuring this out @kreutpet! Sorry I wasn't able to be more help; lots of stuff to do and not much sunlight to get it done in.

Glad you got it working, I'll keep this in mind for the readme!
