### ISSUE TITLE
do not display,just show black screen

### ISSUE THREAD

**Issue by luyaotang** [abrenoch/piwigo-kodi#21]
I used kodi Kodi “Leia”,follow the piwigo-kodi‘s wiki ,down load the zip file,and install it succeed.I apply the correct info with my piwigo site in the plugin confiue zone,and login succeed.
     I can browse the picture list,but when i click to view the picture,it just show a black screen

**Comment by Nibashi** [comment]
Hello,
I have the same problem
It was due to spaces in the url picture
Kodi seems to don't support this
I fix the problem by doing this:
https://github.com/Nibashi/piwigo-kodi/commit/a898c9edeccb09c39c1c33d941768f576bcd387f

**Comment by abrenoch** [comment]
this should be resolved in dc8703888880534346b3f067225296295f1421e6
